name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build-react-app:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run test
 